mutation Register($user: UserInput) {
  register(user: $user) {
    __typename
    message
  }
}

query Me {
  me {
    id
    firstname
    lastname
    email
  }
}

mutation Login($user: LoginInput) {
  login(user: $user) {
    accessToken
    message
    user {
      id
      firstname
      lastname
      email
      role
    }
    isAuthenticated
    success
  }
}

# mutation AddPaymentMethod($token: String!) {
#   addPaymentMethod(token: $token)
# }

# mutation EmailVerification($token: String!) {
#   emailVerification(token: $token)
# }
